### ISSUE TITLE
Unknown note Fb

### ISSUE THREAD

**Issue by Miserlou** [Miserlou/chords2midi#22]
```
p chords2midi/c2m.py i VIIb VIb V7
Unknown note Fb
Traceback (most recent call last):
  File "chords2midi/c2m.py", line 337, in handle
    c2m_obj.handle()
  File "chords2midi/c2m.py", line 135, in handle
    pitch = pychord.utils.note_to_val(note)
  File "/Users/rjones/Projects/chords2midi/env/lib/python2.7/site-packages/pychord/utils.py", line 18, in note_to_val
    raise ValueError("Unknown note {}".format(note))
ValueError: Unknown note Fb
```

**Comment by Miserlou** [comment]
Actually it should be

```
$ p chords2midi/c2m.py i bVII bVI V7
Unknown note Fb
Traceback (most recent call last):
  File "chords2midi/c2m.py", line 337, in handle
    c2m_obj.handle()
  File "chords2midi/c2m.py", line 135, in handle
    pitch = pychord.utils.note_to_val(note)
  File "/Users/rjones/Projects/chords2midi/env/lib/python2.7/site-packages/pychord/utils.py", line 18, in note_to_val
    raise ValueError("Unknown note {}".format(note))
ValueError: Unknown note Fb
```

**Comment by Miserlou** [comment]
https://en.wikipedia.org/wiki/%E2%99%ADVII%E2%80%93V7_cadence
