### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by karhide-xx** [Miserlou/chords2midi#29]
Hi,

I am not sure what is going on but if I run py -m pip install chords2midi I get the error below. Any ideas what is going wrong?  

Defaulting to user installation because normal site-packages is not writeable
Collecting chords2midi
  Using cached chords2midi-0.7.0.tar.gz (4.6 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\tim_w\\AppData\\Local\\Temp\\pip-install-d4pdm4kt\\chords2midi_e3397ee0f75b4079a4d7368745ce859c\\setup.py'"'"'; __file__='"'"'C:\\Users\\tim_w\\AppData\\Local\\Temp\\pip-install-d4pdm4kt\\chords2midi_e3397ee0f75b4079a4d7368745ce859c\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\tim_w\AppData\Local\Temp\pip-pip-egg-info-djfcgpkk'
         cwd: C:\Users\tim_w\AppData\Local\Temp\pip-install-d4pdm4kt\chords2midi_e3397ee0f75b4079a4d7368745ce859c\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\tim_w\AppData\Local\Temp\pip-install-d4pdm4kt\chords2midi_e3397ee0f75b4079a4d7368745ce859c\setup.py", line 12, in <module>
        with open(os.path.join(os.path.dirname(__file__), 'requirements.txt')) as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\tim_w\\AppData\\Local\\Temp\\pip-install-d4pdm4kt\\chords2midi_e3397ee0f75b4079a4d7368745ce859c\\requirements.txt'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/bd/ec/73f2f847cab52b6eed12be1d4ca068e04454bcbbd076210b4f5f90234526/chords2midi-0.7.0.tar.gz#sha256=a5937a5ac3faddb16948298704fc9590b50f07c5c552b104c2a677dbf57dc966 (from https://pypi.org/simple/chords2midi/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached chords2midi-0.3.0.tar.gz (3.9 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\tim_w\\AppData\\Local\\Temp\\pip-install-d4pdm4kt\\chords2midi_deb01cae16a64cc7b332048a23ae5a03\\setup.py'"'"'; __file__='"'"'C:\\Users\\tim_w\\AppData\\Local\\Temp\\pip-install-d4pdm4kt\\chords2midi_deb01cae16a64cc7b332048a23ae5a03\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\tim_w\AppData\Local\Temp\pip-pip-egg-info-zi5o2bfv'
         cwd: C:\Users\tim_w\AppData\Local\Temp\pip-install-d4pdm4kt\chords2midi_deb01cae16a64cc7b332048a23ae5a03\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\tim_w\AppData\Local\Temp\pip-install-d4pdm4kt\chords2midi_deb01cae16a64cc7b332048a23ae5a03\setup.py", line 12, in <module>
        with open(os.path.join(os.path.dirname(__file__), 'requirements.txt')) as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\tim_w\\AppData\\Local\\Temp\\pip-install-d4pdm4kt\\chords2midi_deb01cae16a64cc7b332048a23ae5a03\\requirements.txt'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/00/e5/069c9b8a770a74f664a5bf0913dd6ffcb14f41615f1eca322b3de16e843c/chords2midi-0.3.0.tar.gz#sha256=c87d26dfbcf6a0efca4bb49a37567c1ca47085d357725b2cace90971584ad883 (from https://pypi.org/simple/chords2midi/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached chords2midi-0.2.0.tar.gz (3.8 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\tim_w\\AppData\\Local\\Temp\\pip-install-d4pdm4kt\\chords2midi_62987ef196bb4ec3b9ee7888b9d0cf03\\setup.py'"'"'; __file__='"'"'C:\\Users\\tim_w\\AppData\\Local\\Temp\\pip-install-d4pdm4kt\\chords2midi_62987ef196bb4ec3b9ee7888b9d0cf03\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\tim_w\AppData\Local\Temp\pip-pip-egg-info-hoax0o7t'
         cwd: C:\Users\tim_w\AppData\Local\Temp\pip-install-d4pdm4kt\chords2midi_62987ef196bb4ec3b9ee7888b9d0cf03\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\tim_w\AppData\Local\Temp\pip-install-d4pdm4kt\chords2midi_62987ef196bb4ec3b9ee7888b9d0cf03\setup.py", line 12, in <module>
        with open(os.path.join(os.path.dirname(__file__), 'requirements.txt')) as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\tim_w\\AppData\\Local\\Temp\\pip-install-d4pdm4kt\\chords2midi_62987ef196bb4ec3b9ee7888b9d0cf03\\requirements.txt'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/de/2f/cf2fb5132e8684490717b51975c9ebac708980fcc858c69970835715c1fa/chords2midi-0.2.0.tar.gz#sha256=08809fa6d97c5c31552515a8a7c72fc0ab0238b6c7696c4fd3a5183a5761f1c6 (from https://pypi.org/simple/chords2midi/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached chords2midi-0.1.0.tar.gz (3.1 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\tim_w\\AppData\\Local\\Temp\\pip-install-d4pdm4kt\\chords2midi_cbee172325444a4a9c6428bb70f04cc7\\setup.py'"'"'; __file__='"'"'C:\\Users\\tim_w\\AppData\\Local\\Temp\\pip-install-d4pdm4kt\\chords2midi_cbee172325444a4a9c6428bb70f04cc7\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\tim_w\AppData\Local\Temp\pip-pip-egg-info-i50whcgv'
         cwd: C:\Users\tim_w\AppData\Local\Temp\pip-install-d4pdm4kt\chords2midi_cbee172325444a4a9c6428bb70f04cc7\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\tim_w\AppData\Local\Temp\pip-install-d4pdm4kt\chords2midi_cbee172325444a4a9c6428bb70f04cc7\setup.py", line 12, in <module>
        with open(os.path.join(os.path.dirname(__file__), 'requirements.txt')) as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\tim_w\\AppData\\Local\\Temp\\pip-install-d4pdm4kt\\chords2midi_cbee172325444a4a9c6428bb70f04cc7\\requirements.txt'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/c8/4d/8dd7003bc5edefddae26d43266f7869005093784366aa75d9b17f27edf0a/chords2midi-0.1.0.tar.gz#sha256=309ce124f3893135b324dc1cea1ddd00cddfe7c063bd1128b9eaaaeab0d11ce6 (from https://pypi.org/simple/chords2midi/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement chords2midi (from versions: 0.1.0, 0.2.0, 0.3.0, 0.7.0)
ERROR: No matching distribution found for chords2midi

**Comment by peterjlu** [comment]
Also getting this error -- have you been able to solve this?

**Comment by henrik6** [comment]
The same for me :-(

**Comment by Miserlou** [comment]
This program was not updated for python3 yet. I'll push a new version today.

**Comment by karhide-xx** [comment]
Thanks @Miserlou let me know when and I will test.

**Comment by manchuwook** [comment]
This is what I am getting - as of August 2022.

```
Collecting chords2midi
  Using cached chords2midi-0.7.0.tar.gz (4.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\xxx\AppData\Local\Temp\pip-install-a7krajwp\chords2midi_e73d91f5c09045ada67edf8433d51259\setup.py", line 12, in <module>
          with open(os.path.join(os.path.dirname(__file__), 'requirements.txt')) as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xxx\\AppData\\Local\\Temp\\pip-install-a7krajwp\\chords2midi_e73d91f5c09045ada67edf8433d51259\\requirements.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
WARNING: There was an error checking the latest version of pip.
```

**Comment by purplekeyboard** [comment]
Try running pip pointing directly to the source code. This worked for me on python 3.9.13:
`pip install git+https://github.com/Miserlou/chords2midi`

The package in the pip repo is currently still pointing to 0.7.0
https://pypi.org/project/chords2midi/

but the sourcecode has been updated to [0.9.0](https://github.com/Miserlou/chords2midi/blob/master/setup.py#L17) to be used against [python3](https://github.com/Miserlou/chords2midi/blob/master/setup.py#L39), but looks like it has not been published to the repo yet.

> This is what I am getting - as of August 2022.
> 
> ```
> Collecting chords2midi
>   Using cached chords2midi-0.7.0.tar.gz (4.6 kB)
>   Preparing metadata (setup.py) ... error
>   error: subprocess-exited-with-error
> 
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [6 lines of output]
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "C:\Users\xxx\AppData\Local\Temp\pip-install-a7krajwp\chords2midi_e73d91f5c09045ada67edf8433d51259\setup.py", line 12, in <module>
>           with open(os.path.join(os.path.dirname(__file__), 'requirements.txt')) as f:
>       FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xxx\\AppData\\Local\\Temp\\pip-install-a7krajwp\\chords2midi_e73d91f5c09045ada67edf8433d51259\\requirements.txt'
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed
> 
> × Encountered error while generating package metadata.
> ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for details.
> WARNING: There was an error checking the latest version of pip.
> ```

**Comment by manchuwook** [comment]
That fixed it for me; thanks!

**Comment by tooh** [comment]
Also had this error. 
As noted by @j-ans1 root cause is 

> The package in the pip repo is currently still pointing to 0.7.0
> https://pypi.org/project/chords2midi/
> 
> but the sourcecode has been updated to [0.9.0](https://github.com/Miserlou/chords2midi/blob/master/setup.py#L17) to be used against [python3](https://github.com/Miserlou/chords2midi/blob/master/setup.py#L39), but looks like it has not been published to the repo yet.

Is this package still maintained ?
