### ISSUE TITLE
g minor chords dont work with -r

### ISSUE THREAD

**Issue by FlashlightET** [Miserlou/chords2midi#30]
``` C:\Users\EzoGaming\ch\chords2midi\chords2midi>python c2m.py -o fart.mid -k F Gm -r
list index out of range
Traceback (most recent call last):
  File "c2m.py", line 470, in handle
    c2m_obj.handle()
  File "c2m.py", line 109, in handle
    position = determine(comps, key, True)[0]
IndexError: list index out of range```

**Comment by FlashlightET** [comment]
how did i fix this im getting it again

```
C:\Users\EzoGaming\ch\chords2midi\chords2midi>python c2m.py -k Bb -o Coyo.mid -b 64 -r Bb C Am Dm Gm C D D Bb C Am Dm Bbm C F F
list index out of range
Traceback (most recent call last):
  File "c2m.py", line 470, in handle
    c2m_obj.handle()
  File "c2m.py", line 109, in handle
    position = determine(comps, key, True)[0]
IndexError: list index out of range
```
